apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/hamzahiz55/pfa-project.git
  password: YOUR_GITHUB_TOKEN_HERE
  username: hamzahizi55