# HorizontalPodAutoscaler for the application
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws-s3-manager-hpa
  namespace: aws-s3-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-s3-manager
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU utilization metric
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization metric
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      # Gradual scale down to prevent flapping
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      # Aggressive scale up for handling traffic spikes
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max