# Storage Classes for different cloud providers
# Uncomment the appropriate section for your cloud provider

# ===== AWS EKS =====
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: postgres-storage
# provisioner: ebs.csi.aws.com
# parameters:
#   type: gp3
#   fsType: ext4
#   encrypted: "true"
# reclaimPolicy: Retain
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer

# ===== Google GKE =====
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: postgres-storage
# provisioner: pd.csi.storage.gke.io
# parameters:
#   type: pd-ssd
#   replication-type: regional-pd
#   fstype: ext4
# reclaimPolicy: Retain
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer

# ===== Azure AKS =====
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: postgres-storage
# provisioner: disk.csi.azure.com
# parameters:
#   skuName: Premium_LRS
#   fsType: ext4
#   cachingmode: ReadWrite
# reclaimPolicy: Retain
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer

# ===== Local Development (Docker Desktop/Minikube) =====
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: k8s.io/minikube-hostpath  # or docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate